import logging
from contextlib import AbstractAsyncContextManager
from textwrap import dedent
from typing import TYPE_CHECKING, Any, Self, override

from alembic.util import AutogenerateDiffsDetected, CommandError
from sqlalchemy import Connection, inspect, make_url
from sqlalchemy.ext.asyncio import (
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)

from alembic import command

if TYPE_CHECKING:
    from types import TracebackType

    import sqlalchemy
    from alembic.config import Config
    from sqlalchemy.engine.url import URL
    from sqlalchemy.ext.asyncio import AsyncEngine
    from sqlalchemy.orm import DeclarativeBase


logger = logging.getLogger(__name__)


class DatabaseSchemaMismatchError(Exception):
    def __init__(self, *args: object, db_url: URL | None = None) -> None:
        super().__init__(*args)

        if db_url is not None:
            self.add_note(f"NOTE: Database URL is:\n    {db_url}")


class Database(AbstractAsyncContextManager["Database"]):
    url: sqlalchemy.URL

    engine: AsyncEngine
    sessionmaker: async_sessionmaker[AsyncSession]

    def __init__(self, db_url: str | URL, *, echo: bool = False) -> None:
        url = make_url(db_url)
        self.url = url

        self.init_engine(echo=echo)
        self.sessionmaker = self.get_session = async_sessionmaker(
            bind=self.engine,
            autocommit=False,
            autoflush=False,
            expire_on_commit=False,
            class_=AsyncSession,
        )

        logger.info("Создан и настроен новый объект базы данных")
        logger.debug("Используется URL базы данных: %s", self.url)

    def init_engine(self, *, echo: bool = False) -> None:
        return self._init_engine(echo=echo)

    def _init_engine(
        self, connect_args: dict[Any, Any] | None = None, *, echo: bool = False
    ) -> None:
        if hasattr(self, "engine"):
            msg = "Method `init_engine` must be called only once"
            raise RuntimeError(msg)

        if connect_args is None:
            connect_args = {}

        if self.url.drivername == "sqlite+aiosqlite":
            connect_args.setdefault("autocommit", False)

        self.engine = create_async_engine(
            self.url,
            echo=echo,  # Логирование SQL-запросов
            pool_pre_ping=True,  # Проверка соединения перед использованием
            connect_args=connect_args or {},
        )

    @override
    async def __aenter__(self) -> Self:
        return self

    @override
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool | None:
        await self.engine.dispose()
        logger.info("Объект базы данных был закрыт")

    def get_session(self) -> AsyncSession:
        raise NotImplementedError


class DatabaseChecker:
    declarative_base: type[DeclarativeBase]
    database: Database
    config: Config

    def __init__(
        self,
        base: type[DeclarativeBase],
        database: Database,
        alembic_config: Config,
    ) -> None:
        self.declarative_base = base
        self.database = database
        self.config = alembic_config

    async def check_schema(self) -> bool | None:
        async with self.database.engine.connect() as connection:
            return await connection.run_sync(self._scheck_schema)

    def _scheck_schema(self, connection: Connection) -> bool | None:
        self.config.attributes["connection"] = connection

        try:
            command.check(self.config)
        except AutogenerateDiffsDetected as exc:
            logger.warning("New database upgrade operations detected.")

            for diff in exc.diffs:
                logger.debug("Upgrade: %r", diff)

            return False
        except CommandError as exc:
            logger.warning(str(exc))
            return None

        logger.info("The database fully satisfies the defined schema.")
        return True

    async def upgrade_if_empty(self) -> bool:
        """Upgrade if the database is the database is empty.

        Returns:
            True if an upgrade has been performed.
            False if the database is not empty.
        """
        async with self.database.engine.begin() as connection:
            if not await connection.run_sync(self._check_tables_empty):
                return False

            logger.info("The database is empty, trying to apply migrations.")
            await connection.run_sync(self._upgrade_database_schema)

        return True

    def _check_tables_empty(
        self, connection: Connection, *, schema: str | None = None
    ) -> bool:
        inspector = inspect(connection)

        tables = [
            t
            for t in inspector.get_table_names(schema=schema)
            if t != "alembic_version"
        ]

        logger.debug("В базе данных найдено %i таблиц.", len(tables))

        return not tables

    def _upgrade_database_schema(self, connection: Connection) -> None:
        self.config.attributes["connection"] = connection
        command.upgrade(self.config, "head")

    async def raise_for_differences(
        self, *, upgrade_if_empty: bool = False
    ) -> None:
        schema_differs = await self.check_schema()

        if schema_differs:
            return

        if (
            schema_differs is None
            and upgrade_if_empty
            and await self.upgrade_if_empty()
            and await self.check_schema()
        ):
            return

        msg = dedent("""\
            База данных не соответствует схеме.

            Это значит, что вы изменили содержимое модуля adapters.db.models
            без создания или применения необходимых миграций. Используйте
            команду alembic revision для генерации миграций. Используйте
            alembic upgrade для их применения.
        """)
        raise DatabaseSchemaMismatchError(msg, db_url=self.database.url)
