from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from .schemas import Comment, CommentCreate, Project, ProjectPure


class AbstractProjectsRepo(Protocol):
    async def get(self, id: int) -> Project | None: ...
    async def get_all(self) -> list[Project]: ...
    async def get_all_pure(self) -> list[ProjectPure]: ...
    async def check_item_exists(self, item_id: int) -> bool: ...
    async def get_item_comments(
        self, item_id: int
    ) -> list[Comment] | None: ...
    async def add_comment(
        self, item_id: int, data: CommentCreate
    ) -> Comment | None: ...
