from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    import uuid

    from .schemas import UserCreate, UserRead, UserUpdate


class AbstractUsersRepo(Protocol):
    async def get(self, id: uuid.UUID) -> UserRead | None: ...
    async def get_by_email(self, user_email: str) -> UserRead | None: ...
    async def users_table_empty(self) -> bool: ...
    async def create(
        self, data: UserCreate, *, safe: bool = False
    ) -> UserRead: ...
    async def update(
        self, user_email: str, data: UserUpdate, *, safe: bool = False
    ) -> UserRead | None: ...
    async def delete(self, user_email: str) -> UserRead | None: ...
