"""Rename specifications to projects

Revision ID: 183e7006a92b
Revises: f7d58cc53b81
Create Date: 2026-10-08 22:10:37.836763

"""

from typing import TYPE_CHECKING

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "183e7006a92b"
down_revision: str | Sequence[str] | None = "f7d58cc53b81"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("specifications", "projects")
    op.rename_table(
        "specification_items_categories", "specification_item_categories"
    )

    with op.batch_alter_table("specification_items", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f(
                "fk_specification_items_category_id_specification_items_categories"
            ),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_specification_items_category_id_specification_item_categories"
            ),
            "specification_item_categories",
            ["category_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("specification_rooms", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f(
                "fk_specification_rooms_specification_id_specifications"
            ),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_specification_rooms_specification_id_projects"),
            "projects",
            ["specification_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("projects", "specifications")
    op.rename_table(
        "specification_item_categories", "specification_items_categories"
    )

    with op.batch_alter_table("specification_rooms", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_specification_rooms_specification_id_projects"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_specification_rooms_specification_id_specifications"
            ),
            "specifications",
            ["specification_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("specification_items", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f(
                "fk_specification_items_category_id_specification_item_categories"
            ),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_specification_items_category_id_specification_items_categories"
            ),
            "specification_items_categories",
            ["category_id"],
            ["id"],
            ondelete="CASCADE",
        )
    # ### end Alembic commands ###
