"""Add specification_items table

Revision ID: 1abbfee0a729
Revises:
Create Date: 2026-09-12 18:50:18.312248

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "1abbfee0a729"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "specification_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=1024), nullable=False),
        sa.Column("count", sa.SmallInteger(), nullable=False),
        sa.Column("link", sa.String(length=2083), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "price_currency",
            sa.Enum("RUB", "USD", "EUR", name="currency_code_enum"),
            nullable=True,
        ),
        sa.CheckConstraint(
            "(price IS NULL AND price_currency IS NULL) "
            "OR NOT(price IS NULL OR price_currency IS NULL)",
            name=op.f("ck_specification_items_ux_c_email_or_phone_required"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_specification_items")),
    )
    op.create_table(
        "specification_tag",
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("ordinal_no", sa.Integer(), nullable=False),
        sa.Column("tag", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["specification_items.id"],
            name=op.f("fk_specification_tag_item_id_specification_items"),
        ),
        sa.PrimaryKeyConstraint(
            "item_id", "ordinal_no", name=op.f("pk_specification_tag")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("specification_tag")
    op.drop_table("specification_items")
    # ### end Alembic commands ###
