"""Add ordinal_no to specification_items

Revision ID: 2edb1ebad207
Revises: 9d2e988708b2
Create Date: 2026-09-25 16:35:42.285871

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "2edb1ebad207"
down_revision: str | Sequence[str] | None = "9d2e988708b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("specification_items", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("ordinal_no", sa.Integer(), nullable=True)
        )

    specification_items = sa.table(
        "specification_items",
        sa.column("id", sa.Integer),
        sa.column("ordinal_no", sa.Integer),
    )
    stmt = sa.update(specification_items).values(
        ordinal_no=specification_items.c.id
    )
    op.execute(stmt)

    with op.batch_alter_table("specification_items", schema=None) as batch_op:
        batch_op.alter_column(
            "ordinal_no", existing_type=sa.Integer(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("specification_items", schema=None) as batch_op:
        batch_op.drop_column("ordinal_no")

    # ### end Alembic commands ###
