"""Add specification_items_categories table

Revision ID: 46fda164927b
Revises: 7a81967e82d7
Create Date: 2026-09-12 21:00:55.328575

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "46fda164927b"
down_revision: str | Sequence[str] | None = "7a81967e82d7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "specification_items_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=1024), nullable=False),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_specification_items_categories")
        ),
    )
    with op.batch_alter_table("specification_items", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("category_id", sa.Integer(), nullable=False)
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_specification_items_category_id_specification_items_categories"
            ),
            "specification_items_categories",
            ["category_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("specification_items", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f(
                "fk_specification_items_category_id_specification_items_categories"
            ),
            type_="foreignkey",
        )
        batch_op.drop_column("category_id")

    op.drop_table("specification_items_categories")
    # ### end Alembic commands ###
