"""Add ON DELETE CASCADE to specification_tag

Revision ID: 7a81967e82d7
Revises: 1abbfee0a729
Create Date: 2026-09-12 19:04:32.135232

"""

from typing import TYPE_CHECKING

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "7a81967e82d7"
down_revision: str | Sequence[str] | None = "1abbfee0a729"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("specification_tag", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_specification_tag_item_id_specification_items"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_specification_tag_item_id_specification_items"),
            "specification_items",
            ["item_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("specification_tag", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_specification_tag_item_id_specification_items"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_specification_tag_item_id_specification_items"),
            "specification_items",
            ["item_id"],
            ["id"],
        )

    # ### end Alembic commands ###
