"""Add specification_rooms table

Revision ID: 885e10b7d458
Revises: f49e7db7558f
Create Date: 2026-09-12 23:37:01.099497

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "885e10b7d458"
down_revision: str | Sequence[str] | None = "f49e7db7558f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "specification_rooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("ordinal_no", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_specification_rooms")),
    )
    with op.batch_alter_table(
        "specification_items_categories", schema=None
    ) as batch_op:
        batch_op.add_column(sa.Column("room_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_specification_items_categories_room_id_specification_rooms"
            ),
            "specification_rooms",
            ["room_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "specification_items_categories", schema=None
    ) as batch_op:
        batch_op.drop_constraint(
            batch_op.f(
                "fk_specification_items_categories_room_id_specification_rooms"
            ),
            type_="foreignkey",
        )
        batch_op.drop_column("room_id")

    op.drop_table("specification_rooms")
    # ### end Alembic commands ###
