"""Add lost ForeignKey

Revision ID: 916abd03fb18
Revises: ce5663eef178
Create Date: 2026-09-24 22:00:34.233350

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "916abd03fb18"
down_revision: str | Sequence[str] | None = "ce5663eef178"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("specification_rooms", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("specification_id", sa.Integer(), nullable=False)
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_specification_rooms_specification_id_specifications"
            ),
            "specifications",
            ["specification_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("specification_rooms", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f(
                "fk_specification_rooms_specification_id_specifications"
            ),
            type_="foreignkey",
        )
        batch_op.drop_column("specification_id")

    # ### end Alembic commands ###
