"""Fix nullability

Revision ID: 9d2e988708b2
Revises: 916abd03fb18
Create Date: 2026-09-24 23:26:19.436904

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "9d2e988708b2"
down_revision: str | Sequence[str] | None = "916abd03fb18"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("specification_items", schema=None) as batch_op:
        batch_op.alter_column(
            "link", existing_type=sa.VARCHAR(length=2083), nullable=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("specification_items", schema=None) as batch_op:
        batch_op.alter_column(
            "link", existing_type=sa.VARCHAR(length=2083), nullable=False
        )

    # ### end Alembic commands ###
