"""Add specification_item_comments table

Revision ID: ac40bd21e026
Revises: 2edb1ebad207
Create Date: 2026-09-26 15:15:04.382826

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ac40bd21e026"
down_revision: str | Sequence[str] | None = "2edb1ebad207"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "specification_item_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=4096), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["specification_items.id"],
            name=op.f(
                "fk_specification_item_comments_item_id_specification_items"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_specification_item_comments")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("specification_item_comments")
    # ### end Alembic commands ###
