"""Add created_at to specification_item_comments

Revision ID: b121e204d177
Revises: ac40bd21e026
Create Date: 2026-09-26 17:22:33.561341

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b121e204d177"
down_revision: str | Sequence[str] | None = "ac40bd21e026"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "specification_item_comments", schema=None
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "specification_item_comments", schema=None
    ) as batch_op:
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
