"""Add ordinal_no field to specification_items_categories

Revision ID: f49e7db7558f
Revises: 46fda164927b
Create Date: 2026-09-12 21:17:18.996965

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f49e7db7558f"
down_revision: str | Sequence[str] | None = "46fda164927b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "specification_items_categories", schema=None
    ) as batch_op:
        batch_op.add_column(
            sa.Column("ordinal_no", sa.Integer(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "specification_items_categories", schema=None
    ) as batch_op:
        batch_op.drop_column("ordinal_no")
    # ### end Alembic commands ###
