"""Add author_name to specification_item_comments

Revision ID: f7d58cc53b81
Revises: b121e204d177
Create Date: 2026-09-26 20:52:22.310718

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa
from sqlalchemy import String, update

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f7d58cc53b81"
down_revision: str | Sequence[str] | None = "b121e204d177"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "specification_item_comments", schema=None
    ) as batch_op:
        batch_op.add_column(
            sa.Column("author_name", sa.String(length=128), nullable=True)
        )

    specification_item_comments = sa.table(
        "specification_item_comments",
        sa.column("author_name", String(length=128)),
    )

    stmt = update(specification_item_comments).values(author_name="UNKNOWN")
    op.execute(stmt)

    with op.batch_alter_table(
        "specification_item_comments", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "author_name", existing_type=sa.String(length=128), nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "specification_item_comments", schema=None
    ) as batch_op:
        batch_op.drop_column("author_name")

    # ### end Alembic commands ###
